import type { DisclosureRecord } from './types.js';

// SYNTHETIC DEMO DISCLOSURES
// Every person here is fictional. Every ticker/company pairing is invented for
// the demo. No real filer is represented, and nothing here is attributable to
// any actual person. Amounts are ranges. Published dates are intentionally
// later than transaction dates to demonstrate reporting delay.

function d(iso: string): string {
  return iso; // keep ISO strings as-is; validation happens in the loader
}

export const DEMO_DISCLOSURES: DisclosureRecord[] = [
  {
    id: 'demo-0001',
    ticker: 'ARRX',
    company: 'Aurora Radiomics Inc. (fictional)',
    owner: 'Eleanor Voss (fictional)',
    owner_role: 'Senator',
    tx_type: 'purchase',
    tx_date_min: d('2026-05-02'),
    tx_date_max: d('2026-05-02'),
    published_date: d('2026-06-18'),
    amount_min_usd: 1001,
    amount_max_usd: 15000,
    amendment: false,
    source_name: 'Synthetic demo dataset',
    source_url: null,
    data_mode: 'demo',
    notes: 'Demo record. Owner is fictional; any resemblance to a real filer is coincidental.',
  },
  {
    id: 'demo-0002',
    ticker: 'HRZN',
    company: 'Horizon Freight Systems (fictional)',
    owner: 'Marcus Delgado (fictional)',
    owner_role: 'House member',
    tx_type: 'sale',
    tx_date_min: d('2026-03-11'),
    tx_date_max: d('2026-03-14'),
    published_date: d('2026-05-02'),
    amount_min_usd: 15001,
    amount_max_usd: 50000,
    amendment: false,
    source_name: 'Synthetic demo dataset',
    source_url: null,
    data_mode: 'demo',
  },
  {
    id: 'demo-0003',
    ticker: 'ARRX',
    company: 'Aurora Radiomics Inc. (fictional)',
    owner: 'Eleanor Voss (fictional)',
    owner_role: 'Spouse',
    tx_type: 'purchase',
    tx_date_min: d('2026-05-20'),
    tx_date_max: d('2026-05-20'),
    published_date: d('2026-07-01'),
    amount_min_usd: 1001,
    amount_max_usd: 15000,
    amendment: false,
    source_name: 'Synthetic demo dataset',
    source_url: null,
    data_mode: 'demo',
  },
  {
    id: 'demo-0004',
    ticker: 'CYPW',
    company: 'Cypress Water Utility (fictional)',
    owner: 'Priya Natarajan (fictional)',
    owner_role: 'House member',
    tx_type: 'purchase',
    tx_date_min: d('2026-01-15'),
    tx_date_max: d('2026-01-17'),
    published_date: d('2026-02-27'),
    amount_min_usd: 50000,
    amount_max_usd: 100000,
    amendment: false,
    source_name: 'Synthetic demo dataset',
    source_url: null,
    data_mode: 'demo',
  },
  {
    id: 'demo-0005',
    ticker: 'CYPW',
    company: 'Cypress Water Utility (fictional)',
    owner: 'Priya Natarajan (fictional)',
    owner_role: 'House member',
    tx_type: 'purchase',
    tx_date_min: d('2026-01-15'),
    tx_date_max: d('2026-01-17'),
    published_date: d('2026-04-10'),
    amount_min_usd: 50000,
    amount_max_usd: 100000,
    amendment: true,
    amendment_of: 'demo-0004',
    source_name: 'Synthetic demo dataset',
    source_url: null,
    data_mode: 'demo',
    notes: 'Amendment: corrects filing status of the original transaction record.',
  },
  {
    id: 'demo-0006',
    ticker: 'QLSA',
    company: 'Quailsat Communications (fictional)',
    owner: 'Robert Idowu (fictional)',
    owner_role: 'Senator',
    tx_type: 'sale',
    tx_date_min: d('2026-06-05'),
    tx_date_max: d('2026-06-09'),
    published_date: d('2026-08-01'),
    amount_min_usd: 250001,
    amount_max_usd: 500000,
    amendment: false,
    source_name: 'Synthetic demo dataset',
    source_url: null,
    data_mode: 'demo',
  },
  {
    id: 'demo-0007',
    ticker: 'HRZN',
    company: 'Horizon Freight Systems (fictional)',
    owner: 'Dana Whitfield (fictional)',
    owner_role: 'Spouse',
    tx_type: 'purchase',
    tx_date_min: d('2026-04-22'),
    tx_date_max: d('2026-04-23'),
    published_date: d('2026-06-03'),
    amount_min_usd: 15001,
    amount_max_usd: 50000,
    amendment: false,
    source_name: 'Synthetic demo dataset',
    source_url: null,
    data_mode: 'demo',
  },
  {
    id: 'demo-0008',
    ticker: 'TMBR',
    company: 'Timberline Materials (fictional)',
    owner: 'Oscar Brennan (fictional)',
    owner_role: 'House member',
    tx_type: 'exchange',
    tx_date_min: d('2025-12-08'),
    tx_date_max: d('2025-12-10'),
    published_date: d('2026-01-30'),
    amount_min_usd: 100001,
    amount_max_usd: 250000,
    amendment: false,
    source_name: 'Synthetic demo dataset',
    source_url: null,
    data_mode: 'demo',
  },
  {
    id: 'demo-0009',
    ticker: 'ARRX',
    company: 'Aurora Radiomics Inc. (fictional)',
    owner: 'Robert Idowu (fictional)',
    owner_role: 'Senator',
    tx_type: 'purchase',
    tx_date_min: d('2026-07-14'),
    tx_date_max: d('2026-07-16'),
    published_date: d('2026-08-28'),
    amount_min_usd: 15001,
    amount_max_usd: 50000,
    amendment: false,
    source_name: 'Synthetic demo dataset',
    source_url: null,
    data_mode: 'demo',
  },
  {
    id: 'demo-0010',
    ticker: 'VLTB',
    company: 'Volta Battery Corp (fictional)',
    owner: 'Priya Natarajan (fictional)',
    owner_role: 'House member',
    tx_type: 'sale',
    tx_date_min: d('2026-02-03'),
    tx_date_max: d('2026-02-05'),
    published_date: d('2026-03-20'),
    amount_min_usd: 1001,
    amount_max_usd: 15000,
    amendment: false,
    source_name: 'Synthetic demo dataset',
    source_url: null,
    data_mode: 'demo',
  },
  {
    id: 'demo-0011',
    ticker: 'TMBR',
    company: 'Timberline Materials (fictional)',
    owner: 'Eleanor Voss (fictional)',
    owner_role: 'Spouse',
    tx_type: 'purchase',
    tx_date_min: d('2026-06-30'),
    tx_date_max: d('2026-07-01'),
    published_date: d('2026-08-15'),
    amount_min_usd: 15001,
    amount_max_usd: 50000,
    amendment: false,
    source_name: 'Synthetic demo dataset',
    source_url: null,
    data_mode: 'demo',
  },
  {
    id: 'demo-0012',
    ticker: 'QLSA',
    company: 'Quailsat Communications (fictional)',
    owner: 'Dana Whitfield (fictional)',
    owner_role: 'Child',
    tx_type: 'purchase',
    tx_date_min: d('2026-03-25'),
    tx_date_max: d('2026-03-27'),
    published_date: d('2026-05-14'),
    amount_min_usd: 1001,
    amount_max_usd: 15000,
    amendment: false,
    source_name: 'Synthetic demo dataset',
    source_url: null,
    data_mode: 'demo',
  },
];

export const DEMO_WATCHLIST = [
  {
    id: 'watch-1',
    ticker: 'ARRX',
    company: 'Aurora Radiomics Inc. (fictional)',
    thesis: 'Repeated disclosed buying across two filers; watch for clustering vs. committee timing.',
    added_at: '2026-08-20T10:00:00.000Z',
  },
  {
    id: 'watch-2',
    ticker: 'CYPW',
    company: 'Cypress Water Utility (fictional)',
    thesis: 'Defensive utility with one amended purchase record; amendment reason unknown.',
    added_at: '2026-08-22T09:30:00.000Z',
  },
];

export const DEMO_IDEAS = [
  {
    id: 'idea-1',
    ticker: 'ARRX',
    company: 'Aurora Radiomics Inc. (fictional)',
    thesis: 'Disclosure clustering idea: two owners bought within weeks; compare publication lags.',
    status: 'researching' as const,
    created_at: '2026-08-20T10:05:00.000Z',
  },
  {
    id: 'idea-2',
    ticker: 'HRZN',
    company: 'Horizon Freight Systems (fictional)',
    thesis: 'Mixed signals: one sale by a member, one spouse purchase. Track next filings.',
    status: 'watching' as const,
    created_at: '2026-08-24T14:00:00.000Z',
  },
];

export const DEMO_TRADES = [
  {
    id: 'trade-1',
    ticker: 'ARRX',
    side: 'BUY' as const,
    quantity: 10,
    price: 42.5,
    price_source: 'demo' as const,
    trade_date: '2026-08-21',
    created_at: '2026-08-21T15:04:00.000Z',
    note: 'Demo trade at a labeled demo price (not a market price).',
  },
  {
    id: 'trade-2',
    ticker: 'CYPW',
    side: 'BUY' as const,
    quantity: 5,
    price: 28.1,
    price_source: 'demo' as const,
    trade_date: '2026-08-25',
    created_at: '2026-08-25T16:12:00.000Z',
    note: 'Demo trade at a labeled demo price (not a market price).',
  },
];